import React from 'react'
import { type ColumnDef } from '@tanstack/react-table'
import { Bell, Check, UserCheck, ShieldCheck } from 'lucide-react'
import { useAdminData } from '../../../hooks/useAdminData'
import { adminService } from '../../../services/adminService'
import type { SecurityAlert, AlertStatus } from '../../../types/admin'
import { DataTable } from '../../../components/admin/DataTable'
import { StatusBadge } from '../../../components/admin/StatusBadge'
import { RiskBadge } from '../../../components/admin/RiskBadge'

export function AlertsPage() {
  const alerts = useAdminData(() => adminService.getAlerts())

  function handleAcknowledge(alertId: string) {
    adminService.setAlertStatus(alertId, 'ACKNOWLEDGED')
  }

  function handleAssign(alertId: string) {
    adminService.setAlertStatus(alertId, 'ACKNOWLEDGED', 'Alexander Vance')
  }

  function handleResolve(alertId: string) {
    adminService.setAlertStatus(alertId, 'RESOLVED')
  }

  const columns: ColumnDef<SecurityAlert>[] = [
    {
      accessorKey: 'timestamp',
      header: 'Timestamp',
      cell: ({ row }) => (
        <span className="font-mono text-[11px] text-ink-soft whitespace-nowrap">
          {new Date(row.original.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
        </span>
      ),
    },
    {
      accessorKey: 'severity',
      header: 'Severity',
      cell: ({ row }) => <RiskBadge level={row.original.severity} />,
    },
    {
      accessorKey: 'title',
      header: 'Alert',
      cell: ({ row }) => (
        <div className="font-mono min-w-[200px]">
          <span className="font-semibold text-ink block">{row.original.title}</span>
          <span className="text-[11px] text-ink-soft block">{row.original.description}</span>
        </div>
      ),
    },
    {
      accessorKey: 'tenantName',
      header: 'Tenant / Host',
      cell: ({ row }) => (
        <div className="font-mono text-xs">
          <span className="text-ink block">{row.original.tenantName}</span>
          <span className="text-[10px] text-signal">{row.original.deviceName ?? 'Account-level'}</span>
        </div>
      ),
    },
    {
      accessorKey: 'status',
      header: 'Status',
      cell: ({ row }) => <StatusBadge status={row.original.status} />,
    },
    {
      accessorKey: 'assignedTo',
      header: 'Assigned',
      cell: ({ row }) => (
        <span className="font-mono text-xs text-ink-soft">{row.original.assignedTo ?? 'Unassigned'}</span>
      ),
    },
    {
      id: 'actions',
      header: 'Triage Actions',
      cell: ({ row }) => {
        const alt = row.original
        return (
          <div className="flex items-center justify-end gap-1.5 font-mono text-[10px]">
            {alt.status === 'PENDING' && (
              <button
                type="button"
                onClick={() => handleAcknowledge(alt.id)}
                className="px-2 py-1 rounded bg-surface-2 hover:bg-surface-2 text-ink border border-line flex items-center gap-1"
              >
                <Check className="h-3 w-3" /> Ack
              </button>
            )}
            {!alt.assignedTo && (
              <button
                type="button"
                onClick={() => handleAssign(alt.id)}
                className="px-2 py-1 rounded bg-surface-2 hover:bg-surface-2 text-ink border border-line flex items-center gap-1"
              >
                <UserCheck className="h-3 w-3" /> Assign
              </button>
            )}
            {alt.status !== 'RESOLVED' && (
              <button
                type="button"
                onClick={() => handleResolve(alt.id)}
                className="px-2 py-1 rounded bg-emerald-950/40 hover:bg-emerald-900/40 text-emerald-400 border border-emerald-800/60 flex items-center gap-1"
              >
                <ShieldCheck className="h-3 w-3" /> Resolve
              </button>
            )}
          </div>
        )
      },
    },
  ]

  return (
    <div className="space-y-5">
      <div>
        <h1 className="font-display text-xl font-bold tracking-tight text-ink flex items-center gap-2">
          <Bell className="h-5 w-5 text-signal" />
          SOC Threat Detection Alerts
        </h1>
        <p className="text-xs text-ink-soft font-mono mt-0.5">
          Real-time alerts generated by autonomous security heuristics, multi-factor failures, and kernel hooks.
        </p>
      </div>

      <DataTable
        columns={columns}
        data={alerts}
        searchKey="title"
        searchPlaceholder="Filter alerts by title or description…"
        filterOptions={[
          {
            id: 'severity',
            label: 'Severity',
            options: [
              { label: 'Critical', value: 'CRITICAL' },
              { label: 'High', value: 'HIGH' },
              { label: 'Medium', value: 'MEDIUM' },
              { label: 'Low', value: 'LOW' },
            ],
          },
          {
            id: 'status',
            label: 'Status',
            options: [
              { label: 'Pending', value: 'PENDING' },
              { label: 'Acknowledged', value: 'ACKNOWLEDGED' },
              { label: 'Resolved', value: 'RESOLVED' },
            ],
          },
        ]}
      />
    </div>
  )
}
